---
- name: Ensure Python is in place
  hosts: hopebilling
  gather_facts: no
  strategy: linear
  tasks:
    - raw: dnf -y install python38
    - raw: alternatives --set python /usr/bin/python3

- name: Install Hopebilling on CentOS 8 host
  hosts: hopebilling
  gather_facts: no
  vars:
    percona_repo_url: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    percona_mysql_release: ps80
    remi_repo_url: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    remi_php_release: php74
  tasks:
    - name: Adding Percona repo
      dnf:
        name: "{{ percona_repo_url }}"
        state: present
    - name: Adding REMI repo
      dnf:
        name: "{{ remi_repo_url }}"
        state: present


        #    - name: Add REMI repo
#    - name: Add REMI repo GPG key
#    - name: Install Percona MySQL
#    - name: Install Apache 2
#    - name: Install PHP 7.4 with modules
#    - name: Configure MySQL pool size
#    - name: Ensure MySQL and Apache are enabled and started
#    - name: Set MySQL root password
#    - name: Create ~/.my.cnf
#    - name: Download and unpack hopebilling